name: Clang Tidy
on: [push]
jobs:
  static-analysis:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - run: cmake --workflow --preset ci-check-clang-tidy
