name: Sanitize
on: [push]
jobs:
  sanitize:
    strategy:
      matrix:
        sanitizer: [ub, address, leak, thread]
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - run: cmake --workflow --preset ci-sanitize-${{ matrix.sanitizer }}
